apiVersion: v1
kind: ConfigMap
metadata:
  name: vnf-agent-cfg
data:
  etcd.conf: |
    insecure-transport: true
    dial-timeout: 5000000000
    endpoints:
      - "172.21.174.35:32379"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: vnf-vpp-cfg
data:
  vpp.conf: |
    unix {
      nodaemon
      cli-listen 0.0.0.0:5002
    }
    plugins {
      plugin dpdk_plugin.so {
        disable
      }
    }

---

apiVersion: v1
kind: Pod
metadata:
  name: vnf4
  namespace: default
  labels:
    sfc: "true"
spec:
  containers:
    - name: "vnf4"
      image: ligato/vpp-agent
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      ports:
        - containerPort: 5002
        - containerPort: 9191
      readinessProbe:
        httpGet:
          path: /readiness
          port: 9191
        periodSeconds: 1
      livenessProbe:
        httpGet:
          path: /liveness
          port: 9191
        initialDelaySeconds: 15
      env:
        - name: MICROSERVICE_LABEL
          value: vnf4
      volumeMounts:
        - name: vpp-config
          mountPath: /etc/vpp
        - name: agent-config
          mountPath: /opt/vpp-agent/dev
        - name: memif-sockets
          mountPath: /tmp
  volumes:
  - name: vpp-config
    configMap:
      name: vnf-vpp-cfg
  - name: agent-config
    configMap:
      name: vnf-agent-cfg
  - name: memif-sockets
    hostPath:
      path: /tmp
  nodeSelector:
    role: anti-affinity

---